{% set name = "fakecbed" %}
{% set version = "0.3.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/fakecbed-{{ version }}.tar.gz
  sha256: 725c2caa738339382e2fa483722c97edb702bbaf069e033617bf7eae50641192

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - setuptools
    - wheel
    - setuptools-scm
    - pip
  run:
    - python >={{ python_min }}
    - distoptica >=0.3.0
    - hyperspy

test:
  imports:
    - fakecbed
  commands:
    - pip check
  requires:
    - python {{ python_min }}
    - pip

about:
  home: https://pypi.org/project/fakecbed/
  summary: A Python library for generating quickly images that imitate convergent beam electron diffraction patterns.
  dev_url: https://github.com/mrfitzpa/fakecbed
  license: GPL-3.0-only
  license_file: LICENSE

extra:
  recipe-maintainers:
    - mrfitzpa
