{% set name = "fakecbed" %}
{% set version = "0.5.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/fakecbed-{{ version }}.tar.gz
  sha256: a0a36b76dece200cc9d57f933b89c53350a1604613efc8ee0e03315bfe48a4bb

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - setuptools
    - wheel
    - setuptools-scm
    - pip
  run:
    - python >={{ python_min }}
    - distoptica >=0.4.0
    - empix
    - hyperspy

test:
  imports:
    - fakecbed
  commands:
    - pip check
  requires:
    - python {{ python_min }}
    - pip

about:
  home: https://pypi.org/project/fakecbed/
  summary: A Python library for generating quickly images that imitate convergent beam electron diffraction patterns.
  dev_url: https://github.com/mrfitzpa/fakecbed
  license: GPL-3.0-only
  license_file: LICENSE

extra:
  recipe-maintainers:
    - mrfitzpa
